export const ADD_NEW_LIST = 'ADD_NEW_LIST';

export const REQUEST_AUTHORIZATION = 'REQUEST_AUTHORIZATION';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const LOG_OUT = 'LOG_OUT';
export const PROMPT_ERROR = 'PROMPT_ERROR';