export const ADD_NEW_LIST = 'ADD_NEW_LIST';

export const REQUEST_AUTHORIZATION = 'REQUEST_AUTHORIZATION';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const LOG_OUT = 'LOG_OUT';
export const PROMPT_ERROR = 'PROMPT_ERROR';
export const EDIT_LIST = 'EDIT_LIST';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const UPDATE_DATABASE = 'UPDATE_DATABASE';
export const GET_FROM_DATABASE = 'GET_FROM_DATABASE';
export const SAVE_DATA_FROM_DATABASE = 'SAVE_DATA_FROM_DATABASE';
export const SAVE_DATA_TO_DATABASE = 'SAVE_DATA_TO_DATABASE';
export const SAVED_DATA_TO_DATABASE = 'SAVED_DATA_TO_DATABASE';
export const REMOVE_FROM_DATABASE = 'REMOVE_FROM_DATABASE';
